name: hinduism
description: "An open source Flutter project for Hinduism."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #backend
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.1.0
  #state-management
  flutter_riverpod: ^3.3.1
  #assets
  cached_network_image: ^3.3.0
  flutter_gen: ^5.11.0
  #responsive
  flutter_screenutil: ^5.9.3
  #fonts
  google_fonts: ^8.0.2
  #webview
  # webview_flutter: ^4.13.0
  cupertino_icons: ^1.0.6
  #http client
  dio: ^5.8.0+1
  #http client generation
  retrofit: ^4.6.0
  #json de/serialization
  freezed_annotation: 
  json_annotation: 
  #routing
  go_router: ^17.1.0
  #app flavor
  flutter_flavor: ^3.1.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  connectivity_plus: ^7.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  retrofit_generator: 
  json_serializable: 

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  fonts:
    - family: Shamim Cholontika
      fonts:
        - asset: assets/fonts/Shamim Cholontika/LiShamimCholontikaANSIV1-Regular.ttf
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-VariableFont_wdth,wght.ttf
