// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDddTlfA8RVT9usGV6WB-hLvOVTddoXsPc',
    appId: '1:69370668855:web:1384cf857a01797f371cb2',
    messagingSenderId: '69370668855',
    projectId: 'hinduism-f8826',
    authDomain: 'hinduism-f8826.firebaseapp.com',
    storageBucket: 'hinduism-f8826.appspot.com',
    measurementId: 'G-70Q8WM97CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiybJjDpHXwgY3barmNurycSEHWVPXUDU',
    appId: '1:69370668855:android:6e8264d1dfda1cf7371cb2',
    messagingSenderId: '69370668855',
    projectId: 'hinduism-f8826',
    storageBucket: 'hinduism-f8826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuN7HCyKvZN7qnjWnvqP8GWZVgYee9WmU',
    appId: '1:69370668855:ios:d4e6acef16e1e28e371cb2',
    messagingSenderId: '69370668855',
    projectId: 'hinduism-f8826',
    storageBucket: 'hinduism-f8826.appspot.com',
    iosBundleId: 'com.example.hinduism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuN7HCyKvZN7qnjWnvqP8GWZVgYee9WmU',
    appId: '1:69370668855:ios:d4e6acef16e1e28e371cb2',
    messagingSenderId: '69370668855',
    projectId: 'hinduism-f8826',
    storageBucket: 'hinduism-f8826.appspot.com',
    iosBundleId: 'com.example.hinduism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDddTlfA8RVT9usGV6WB-hLvOVTddoXsPc',
    appId: '1:69370668855:web:47c69411d77997c5371cb2',
    messagingSenderId: '69370668855',
    projectId: 'hinduism-f8826',
    authDomain: 'hinduism-f8826.firebaseapp.com',
    storageBucket: 'hinduism-f8826.appspot.com',
    measurementId: 'G-EWREMYZ7GE',
  );
}
